### ISSUE TITLE
README.markdown contains "Content unavailable" link

### ISSUE THREAD

**Issue by DaleEMoore** [andydotxyz/xsm#1]
I found the README.markdown [Community link](http://groups.google.com/group/xsm-users/) does not allow me access with a "Content unavailable" error message.

Near: `If you are interested in support or just catching up you can join our google group - http://groups.google.com/group/xsm-users/`

**Comment by andydotxyz** [comment]
Thanks for pointing it out. This repo is very old and the community was closed some time ago.
I removed the link and will archive the repo.
